seed: 42
max_epochs: 100
nbatches: 1
log_every_n_steps: 1
update_axis_every_n_epochs: 20
learning_rate: 0.1

equilibrium:
  _target_: inverse-3d-mhd
  nfp: 19
  p: [18000, -36000, 18000]
  iota: [-1.0, -1.5]
  Rb:
    - [0., 10., 0.]
    - [0.0, 1., 0.3]
  Zb:
    - [0., 0., 0.]
    - [0, 1., -0.3]
  Ra: [10.4, 0.1]
  Za: [0.0, -0.1]
  phi_edge: 1.0
  wout_path: data/wout_HELIOTRON.nc
  sym: true
  ns: 51
  ntheta: 16
  nzeta: 18
  max_mpol: 2
  max_ntor: 1

