seed: 420
max_epochs: 200
nbatches: 1
log_every_n_steps: 1
update_axis_every_n_epochs: 20
learning_rate: 0.1

equilibrium:
  _target_: inverse-3d-mhd
  nfp: 19
  p: [0]
  iota: [-1.0, -1.5]
  Rb: [ [0., 10., 0.], [0.0, 1., 0.3] ]
  Zb: [ [0., 0., 0.], [0, 1., -0.3] ]
  Ra: 10
  Za: 0.0
  phi_edge: 1.0
  wout_path: data/wout_HELIOTRON_0BETA.nc
  sym: true
  ns: 16
  ntheta: 16
  nzeta: 16
  max_mpol: 2
  max_ntor: 1


